layout_ckpt: /data/inr/llm/DIFF_CD/Diffusor/outputsV3/layout_d3pm_masked_sparse_80k
layout_checkpoint: 10000
layout_diffusion_type: d3pm
domain: urban
domain_cond_scale: 1.0
controlnet_ckpt: /data/inr/llm/DIFF_CD/Diffusor/outputsV3/controlnet_ratio_lora_ckpt18000_layout80000/checkpoint-40000
base_model: /home/nvidia/.cache/huggingface/hub/models--runwayml--stable-diffusion-v1-5/snapshots/451f4fe16113bff5a5d2269ed5ad43b0592e9a14

save_dir: /data/inr/llm/DIFF_CD/Diffusor/outputsV3/results_generator/gpu7
ratios: "building:0.4"
prompt: a high-resolution satellite image of an urban area

image_size: 1024
num_inference_steps_layout: 50
num_inference_steps_image: 30
guidance_scale: 1.0
guidance_rescale: 0.0
control_scale: 1.0

seed: 40000
dtype: fp16
device: cuda:0
sampler: ddim
