pretrained_model_name_or_path: /home/nvidia/.cache/huggingface/hub/models--runwayml--stable-diffusion-v1-5/snapshots/451f4fe16113bff5a5d2269ed5ad43b0592e9a14
data_root: /data/inr/llm/Datasets/LOVEDA
dataset: loveda
output_dir: /data/inr/llm/DIFF_CD/Diffusor/outputsV3/controlnet_ratio_lora_ckpt18000_layout80000

image_size: 1024
layout_size: 256
ignore_index: 255
loveda_split: Train
loveda_domains: Urban,Rural
prompt: a high-resolution satellite image
prompt_urban: A high-resolution satellite image of an urban area
prompt_rural: A high-resolution satellite image of a rural area

learning_rate: 1.0e-5
train_batch_size: 12
max_train_steps: 140000
checkpointing_steps: 1000

mask_mix_prob: 0.5
cfg_dropout_prob: 0.1
cond_dropout_prob: 0.05
snr_gamma: 5.0
noise_offset: 0.0

lora_weight_name: pytorch_lora_weights.safetensors
lora_scale: 1.0
lora_unfreeze_step: -1

sample_num_inference_steps_layout: 200
sample_num_inference_steps: 50

seed: 123
mixed_precision: fp16
